'use client';

import { useState } from 'react';
import { ArrowRight, Check, Code2, FileCode2, GitBranch, Globe2, LayoutTemplate, ListChecks, Mail, MessageSquare, MousePointer2, Play, RotateCcw, Smartphone, Target, Upload, UserRound } from 'lucide-react';
import './build-workshop.css';

export const buildSteps = [
  {label:'Requirements',title:'Define a useful outcome.',caption:'Who will use it? What goes in? What should come out?',notes:'Start by building requirements with the employee who will use the tool. Define the user, the task, sample inputs, the desired result, constraints, and a visible definition of success. Ask the coding agent to interview you when anything is missing. Use an example to make acceptance concrete. This stage is about agreeing what useful means before building screens.'},
  {label:'Design',title:'Make the idea visible.',caption:'Sketch the flow. Agree on the screen. Test the idea.',notes:'Ask for a simple design or wireframe before implementation. Map input to action to result, including the empty state and what happens if input is missing. Review the proposed layout with the intended user. Change the design while it is cheap to change. The animated wireframe is illustrative; it does not prescribe fields for the live app.'},
  {label:'Build',title:'Turn the design into a working tool.',caption:'Build a small version. Try a sample. Repeat.',notes:'Give the agreed requirements and design to the coding agent. Build a small working version, then try it with sample data. Compare the result with the requirements and revise the design or implementation. The sample button demonstrates a local illustrative UI only. In the live demonstration, we will work in Codex with voice; the specific app inputs and outputs remain to be agreed with the audience.'},
  {label:'GitHub',title:'Give your project a home.',caption:'Create a GitHub account, then a repository for the project.',notes:'Create a GitHub account if you do not already have an approved one and verify its email address. Create a repository, which stores project files and version history. Follow the organization’s account and repository ownership practices. Choose visibility deliberately. The displayed account and repository are illustrative; this slide does not create an account or repository.'},
  {label:'Upload',title:'Save the software and its history.',caption:'Upload or push the project files to the repository.',notes:'Upload the software files through GitHub or push them from the coding workspace. Include the project source, dependency instructions and build configuration needed to reproduce the site. Review the files before committing and keep credentials and private data out. The illustrated HTML/CSS/JavaScript files represent a simple static project. A framework app may require a build workflow rather than uploading source as the published site.'},
  {label:'Pages',title:'Turn the project into a public site.',caption:'Configure GitHub Pages. Build, publish, and open the URL.',notes:'For a static browser-based site, configure Settings → Pages and choose a branch/folder or GitHub Actions publishing workflow. Framework projects usually need a build step that produces the static site artifact. Wait for deployment to succeed and open the actual public URL. GitHub Pages hosts static content; a backend, database, authentication service or AI API needs appropriate additional hosting. The animation illustrates publishing and does not deploy anything.'},
  {label:'QA',title:'Test the experience people will use.',caption:'Check the real URL, the buttons, and small screens.',notes:'QA means quality assurance: test the deployed site, not just the development preview. Try the main workflow with sample data and verify its output. Check links, buttons, keyboard use, images and styles, mobile layout, empty/error states, and browser errors. A successful deployment alone is not proof that the app works. The animated checks are illustrative, not a report of tests on the eventual live-demo app.'},
  {label:'Refine',title:'Use feedback to make the next version.',caption:'Improve one thing. Publish again. Try it together.',notes:'Collect specific feedback from someone using the tool. Translate it into a requirement, improve the design or code, test the change, and publish the next version. This is the handoff into the live demo: build, use and refine together in Codex with voice. Use sample data and agree the app’s exact requirements with the audience; no particular résumé fields or biography format are assumed.'},
] as const;

function BrowserBar({label}:{label:string}){return <div className="workshop-browser-bar"><i/><i/><i/><span>{label}</span></div>;}

function Requirements(){return <div className="requirements-art"><div className="idea-notes"><div><UserRound/>The user</div><div><FileCode2/>The input</div><div><Target/>The result</div></div><ArrowRight className="requirements-arrow"/><div className="requirements-sheet"><span className="workshop-art-label">The requirements</span><h3>What does “good” look like?</h3>{['A clear purpose','A useful result','A way to check it'].map((s,i)=><p key={s} style={{animationDelay:`${i*.3+.5}s`}}><Check/>{s}</p>)}<div className="requirements-signoff"><ListChecks/>Ready to design</div></div></div>;}

function Design(){return <div className="design-art"><div className="design-ruler"><span>Input</span><ArrowRight/><span>Action</span><ArrowRight/><span>Result</span></div><div className="wireframe-window"><BrowserBar label="Design preview"/><div className="wireframe-body"><div className="wireframe-input"><span>Your input</span><i/><i/></div><div className="wireframe-action">Run the workflow <ArrowRight size={16}/></div><div className="wireframe-output"><span>A useful result</span><i/><i/><i/></div></div><MousePointer2 className="design-pointer"/></div><p className="workshop-art-caption">Agree on the experience before writing the software.</p></div>;}

function Construction({ran,onRun}:{ran:boolean;onRun:()=>void}){return <div className={`construction-art ${ran?'sample-complete':''}`}><div className="construction-editor"><span><Code2/>Build the workflow</span>{['read(input)','apply(rules)','return(result)'].map((s,i)=><code key={s} style={{animationDelay:`${i*.35}s`}}>{s}</code>)}<small>Illustrative code</small></div><ArrowRight className="construction-arrow"/><div className="constructed-window"><BrowserBar label="Working preview"/><div className="constructed-body"><p className="sample-loaded"><Check/>Sample input loaded</p><button onClick={onRun}><Play size={15}/>{ran?'Reset sample':'Try the sample'}</button><div className="constructed-result">{ran?<><Check/><strong>Result ready</strong><span>Now compare it with the requirements.</span></>:<><LayoutTemplate/><span>A small version you can use.</span></>}</div></div></div><p className="build-iteration"><RotateCcw/>Learn from the result. Revisit the brief, design, or build.</p></div>;}

function Account(){return <div className="github-account-art"><div className="account-card"><GitBranch/><h3>Your GitHub account</h3><p><Mail/>Email verified <Check/></p></div><ArrowRight/><div className="repository-card"><FolderIcon/><span>New repository</span><h3>my-first-tool</h3><small>Your files + version history</small></div></div>;}
function FolderIcon(){return <GitBranch className="repository-icon"/>;}

function UploadFiles(){return <div className="upload-art"><div className="upload-files">{['index.html','styles.css','app.js'].map((file,i)=><div key={file} style={{animationDelay:`${i*.3}s`}}><FileCode2/>{file}</div>)}</div><div className="upload-bridge"><Upload/><span>Upload / push</span></div><div className="repository-card upload-repository"><GitBranch className="repository-icon"/><span>my-first-tool</span><h3>Version 1</h3><p><Check/>Project saved</p></div><p className="workshop-art-caption">Illustrative static project</p></div>;}

function Publish(){return <div className="publish-art"><div className="publish-pipeline">{['Build','Publish','Live'].map((s,i)=><div key={s} style={{animationDelay:`${i*.45}s`}}><Check/><span>{s}</span></div>)}</div><div className="published-window"><BrowserBar label="GitHub Pages"/><div><Globe2/><h3>Your site is live.</h3><span>your-account.github.io/your-tool</span></div></div><p className="workshop-art-caption">A public URL for your static site.</p></div>;}

function Quality(){return <div className="quality-art"><div className="device-checks"><div className="qa-desktop"><BrowserBar label="Test the real site"/><div className="qa-layout"><i/><i/><i/><Check/></div></div><div className="qa-phone"><Smartphone/><div><Check/></div></div><div className="qa-scan"/></div><div className="quality-list">{['Links & buttons','Small screens','Expected result'].map((s,i)=><p key={s} style={{animationDelay:`${i*.35+.4}s`}}><Check/>{s}</p>)}</div></div>;}

function Refine(){return <div className="refine-art"><div className="feedback-note"><MessageSquare/>“Make the result clearer.”</div><div className="version-comparison"><div className="old-version"><span>Version 1</span><i/><i/><i/><i/></div><ArrowRight/><div className="new-version"><span>Version 2</span><h3>A clearer result.</h3><p><Check/>Organized</p><p><Check/>Easy to act on</p></div></div><p className="live-demo-callout"><Play/>Live demo: build, use, and refine together.</p></div>;}

export default function BuildWorkshop({phase,active}:{phase:number;active:boolean}) {
  const [replay,setReplay]=useState(0),[ran,setRan]=useState(false);
  const implementation=phase>=3,local=implementation?phase-3:phase,items=implementation?buildSteps.slice(3):buildSteps.slice(0,3),step=buildSteps[phase];
  return <div className={`build-workshop ${active?'workshop-active':''} ${implementation?'implementation-page':'creation-page'}`}>
    <aside className="workshop-guide"><p className="micro">{implementation?'02 / 02 · Implementation':'01 / 02 · Creation'}</p><ol className="workshop-steps">{items.map((s,i)=><li key={s.label} className={i===local?'current':i<local?'complete':''} aria-current={i===local?'step':undefined}><span>{i<local?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{s.label}</li>)}</ol><p>{step.caption}</p></aside>
    <div className="workshop-theatre"><div className="workshop-top"><span>Illustrative process</span><button aria-label="Replay build step" onClick={()=>{setReplay(replay+1);setRan(false);}}><RotateCcw size={14}/>Replay</button></div><h2>{step.title}</h2><div className={`workshop-stage workshop-stage-${phase}`} key={replay}>{phase===0?<Requirements/>:phase===1?<Design/>:phase===2?<Construction ran={ran} onRun={()=>setRan(!ran)}/>:phase===3?<Account/>:phase===4?<UploadFiles/>:phase===5?<Publish/>:phase===6?<Quality/>:<Refine/>}</div></div>
  </div>;
}
