export const agentExamples = [
  { id:'inbox', label:'Inbox', title:'Start the day ahead.', trigger:'Every weekday morning', action:'Find unresolved requests, rank what needs you, and prepare follow-ups.', starter:'Start today: one inbox folder + your priority rules.', review:'You review replies and filing changes.' },
  { id:'website', label:'Website', title:'Keep profiles moving.', trigger:'When a bio or headshot arrives', action:'Match the files, flag what is missing, and prepare a website-ready profile.', starter:'Start today: an approved bio, photo + profile template.', review:'You approve the profile before publishing.' },
  { id:'photoshoot', label:'Photoshoots', title:'Make the schedule work.', trigger:'When availability changes', action:'Match calendars, locations and preferences. Propose slots and flag conflicts.', starter:'Start today: availability + the shoot requirements.', review:'You approve bookings and invitations.' },
  { id:'talent', label:'Talent Book', title:'Catch gaps before the deadline.', trigger:'Each Friday', action:'Compare the roster with bios and photos. Flag stale entries and possible duplicates.', starter:'Start today: the current roster + one asset folder.', review:'You confirm corrections and merges.' },
] as const;

export const webinarSteps = [
  { label:'The brief', title:'Create one source of truth.', tool:'Excel + SharePoint', action:'Add event details, approved links, registrations and contact permissions.', notes:'Example Microsoft setup, not a claim about Canopy’s current stack. Create an Excel table in SharePoint with Event ID, start time and time zone, approved registration/replay links, recipient email, contact permission, attendance, and send status. Store approved event copy alongside it. Start with a small sample or a webinar-platform export. Agree on what counts as ready; the agent flags missing data instead of guessing.' },
  { label:'The trigger', title:'Give it a starting signal.', tool:'Power Automate', action:'Schedule checks for reminders and follow-ups. Recheck the current event details.', notes:'Create a scheduled cloud flow to check the event table. Example timing: 24 hours before, 1 hour before, and 2 hours after the event. Use the stored time zone, skip cancelled events, and wait for a verified attendance export and approved replay link before follow-up. These are preparation triggers; they do not bypass approval or guarantee a delivery time. Ordinary automation handles the timing; the agent handles context and exceptions.' },
  { label:'The audience', title:'Give each group the right next step.', tool:'Excel rules + agent review', action:'Separate attendees and no-shows. Hold unknowns and duplicate records for review.', notes:'Read registration and attendance exports into the event table. Use explicit data, not AI guesses, for who attended and who may be contacted. Deduplicate by a verified recipient identifier; hold conflicting or unknown records for Serena. A unique Event ID + Recipient + Message Type key prevents duplicate delivery. The agent explains exceptions and can interpret supplied questions to suggest relevant follow-up material.' },
  { label:'The agent', title:'Turn context into useful messages.', tool:'Copilot Studio', action:'Create a webinar agent to tailor drafts, use approved material, and flag missing answers.', notes:'Configure a Copilot Studio agent with the approved event brief, tone, audience rules, and access to the draft tool or flow. Have it prepare reminders plus separate attendee and no-show follow-ups. Ask it to use supplied questions when relevant, check dates and approved link values, and flag anything it cannot verify. The event-trigger payload or calling flow supplies the relevant event and audience context. Keep timing, recipient rules and delivery in explicit workflow steps. Approved connections, enabled features and applicable licensing are prerequisites.' },
  { label:'The handoff', title:'Approve. Deliver. Keep a record.', tool:'Power Automate Approvals + Outlook', action:'Test with yourself. Serena approves the recipient list and messages before delivery.', notes:'Use Start and wait for an approval, with Serena as the reviewer of both the messages and recipient groups. Only the approved branch can call Outlook Send an email and update the send log. If rejected or expired, hold the messages; do not silently send. Test on internal sample addresses first. Log successful sends and exceptions, check the unique send key before retrying, and route replies for human review. The on-slide approval button only animates a fictional example; it never sends email. Begin with one supervised run before enabling recurring triggers.' },
] as const;

export const webinarPrompt = 'Help me design a webinar communications agent. Ask for the event brief, approved links, registration and attendance data, contact permissions, tone and timing. Prepare reminder drafts and separate follow-ups for attendees and no-shows using only approved material. Flag missing or conflicting records and unanswered questions. Put timing, recipient selection and duplicate-send checks in explicit workflow rules. Show Serena the recipient groups and messages for approval; send only through an authorized delivery step after approval and keep a send log. Start with a small internal test. Ask which tools and connections are available before proposing implementation.';
